### ISSUE TITLE
Slash Commands not working

### ISSUE THREAD

**Issue by proudparrot2** [L0SER8228/snowsgiving-bot#2]
I tried to run the commands, but they are not working. Don't you have to register them or something?

**Comment by proudparrot2** [comment]
https://replit.com/@ParrotDev/snowballer here is my code

**Comment by LackyPal** [comment]
Check and uncomment this line then restart your bot.
Remember slash command takes approx 1hour to register globally so be patient
https://github.com/L0SER8228/snowsgiving-bot/blob/0dfa7bb9796d1a3dcd185611b0b0d51057ee42af/src/handlers/CommandHandler.js#L26

**Comment by proudparrot2** [comment]
i already did that so i am gonna try again

**Comment by proudparrot2** [comment]
It worked! Thanks!

**Comment by proudparrot2** [comment]
Oops I have more problems... When I try running /leaderboard /throw and /stats, it says invalid application command. Help? Sorry, I'm new to Slash Commands

**Comment by LackyPal** [comment]
Show full error

**Comment by proudparrot2** [comment]
Nothing shows up in console.

**Comment by proudparrot2** [comment]
Please help? Do you have a copy of the code that you know works?
