### ISSUE TITLE
Invalid Application Command error

### ISSUE THREAD

**Issue by proudparrot2** [L0SER8228/snowsgiving-bot#3]
Hello again,
When I try to run /throw, /stats, and /leaderboard, it loads for a hot second then displays the error Invalid Application Command. I have not changed any code inside those commands, so I do not know why this is happening.

Sorry, I have never done Slash Commands before so I don't know how to fix them.

**Comment by LackyPal** [comment]
If you don't know about slash command, I can't help you . I'm using the same code, it's working fine for me
